### ISSUE TITLE
Invalid JSON error while importing backup

### ISSUE THREAD

**Issue by Mario0051** [Exploshe/Reverse1999-Summon-Tracker#1]
I am trying to import my backup from the old website to the new website and this error is encountered:
![image](https://github.com/Exploshe/Reverse1999-Summon-Tracker/assets/16366524/bde32d3f-4af4-4140-b718-c2a05bdbf281)

**Comment by Exploshe** [comment]
try importing again, let me know if it works

**Comment by Mario0051** [comment]
It would be nice if there was a success message. It does work now though.
